### ISSUE TITLE
作者您好~我最近也在做这方面的研究，遇到一些问题~希望与您讨论一下~

### ISSUE THREAD

**Issue by ghost** [zxetb/3D-model-retrieval-system#1]

**Comment by zHashBrown** [comment]
欢迎讨论！issue里留言即可

**Comment by FeiFanMoKe** [comment]
我用了您提供的方法(blender)像获得12视图，可是他并不能读取off文件，但是其他类型的文件(比如stl等)是可以的，所以不知道是怎么回事

**Comment by ghost** [comment]
> 欢迎讨论！issue里留言即可

我用了您提供的方法(blender)像获得12视图，可是他并不能读取off文件，但是其他类型的文件(比如stl等)是可以的，所以不知道是怎么回事，不知是不是我的版本有问题

**Comment by zHashBrown** [comment]
> > 欢迎讨论！issue里留言即可
> 
> 我用了您提供的方法(blender)像获得12视图，可是他并不能读取off文件，但是其他类型的文件(比如stl等)是可以的，所以不知道是怎么回事，不知是不是我的版本有问题

blender软件在之后的版本取消了对off文件的支持，需要自己设置导入，具体可以参考https://blog.csdn.net/jorg_zhao/article/details/86309774
我在BlenderPhong文件夹里也放了对off文件支持的脚本和设置好的黑底场景，按照这个教程设置就可以后台使用了。

**Comment by ghost** [comment]
> > > 欢迎讨论！issue里留言即可
> > 
> > 
> > 我用了您提供的方法(blender)像获得12视图，可是他并不能读取off文件，但是其他类型的文件(比如stl等)是可以的，所以不知道是怎么回事，不知是不是我的版本有问题
> 
> blender软件在之后的版本取消了对off文件的支持，需要自己设置导入，具体可以参考https://blog.csdn.net/jorg_zhao/article/details/86309774
> 我在BlenderPhong文件夹里也放了对off文件支持的脚本和设置好的黑底场景，按照这个教程设置就可以后台使用了。

我有看到这篇博文，但是我在导入这个OFF Addon的时候一直报错
![image](https://user-images.githubusercontent.com/28892927/87927016-1ba65b80-cab5-11ea-98d9-b0cb1fb0a51b.png)
顺带一提，我下载的是百度的免安装版~版本是2.79

**Comment by zHashBrown** [comment]
> > > > 欢迎讨论！issue里留言即可
> > > 
> > > 
> > > 我用了您提供的方法(blender)像获得12视图，可是他并不能读取off文件，但是其他类型的文件(比如stl等)是可以的，所以不知道是怎么回事，不知是不是我的版本有问题
> > 
> > 
> > blender软件在之后的版本取消了对off文件的支持，需要自己设置导入，具体可以参考https://blog.csdn.net/jorg_zhao/article/details/86309774
> > 我在BlenderPhong文件夹里也放了对off文件支持的脚本和设置好的黑底场景，按照这个教程设置就可以后台使用了。
> 
> 我有看到这篇博文，但是我在导入这个OFF Addon的时候一直报错
> ![image](https://user-images.githubusercontent.com/28892927/87927016-1ba65b80-cab5-11ea-98d9-b0cb1fb0a51b.png)
> 顺带一提，我下载的是百度的免安装版~版本是2.79

你用的是教程里的拓展脚本吗？教程里的blender-off-addon更新到最新版了，我用的我项目里旧版的拓展脚本在2.79下测试是没有问题的

**Comment by ghost** [comment]
> > > > > 欢迎讨论！issue里留言即可
> > > > 
> > > > 
> > > > 我用了您提供的方法(blender)像获得12视图，可是他并不能读取off文件，但是其他类型的文件(比如stl等)是可以的，所以不知道是怎么回事，不知是不是我的版本有问题
> > > 
> > > 
> > > blender软件在之后的版本取消了对off文件的支持，需要自己设置导入，具体可以参考https://blog.csdn.net/jorg_zhao/article/details/86309774
> > > 我在BlenderPhong文件夹里也放了对off文件支持的脚本和设置好的黑底场景，按照这个教程设置就可以后台使用了。
> > 
> > 
> > 我有看到这篇博文，但是我在导入这个OFF Addon的时候一直报错
> > ![image](https://user-images.githubusercontent.com/28892927/87927016-1ba65b80-cab5-11ea-98d9-b0cb1fb0a51b.png)
> > 顺带一提，我下载的是百度的免安装版~版本是2.79
> 
> 你用的是教程里的拓展脚本吗？教程里的blender-off-addon更新到最新版了，我用的我项目里旧版的拓展脚本在2.79下测试是没有问题的

好了 ，可以了，谢谢耐心解答！没注意到你的项目里面有脚本，刚刚看到你上面说的你项目里面也有才发现，现在已经可以了，感谢！
