### ISSUE TITLE
测试集检索的map只有0.19%

### ISSUE THREAD

**Issue by 20TianTian22** [zxetb/3D-model-retrieval-system#12]
我train了136000steps之后在原model net40测试集上执行map_test.py，map只有0.0019，正常吗

**Comment by zHashBrown** [comment]
如果你训练集用的是blender生成的图片，你的测试集也应该用blender生成的图

**Comment by 20TianTian22** [comment]
感谢回复！
我想请教一下模型检索的话，您的算法中，ap是由检索list中返回的模型是否在其category的range中的比例的高低来决定。
如果我想比较检索后的retrieval list中的模型与输入模型的相似度的话，可不可以拿他们对应的generated feature（fc7的output）进行一个欧氏距离的比较？

**Comment by zHashBrown** [comment]
可以，我在检索的时候已经用过欧氏距离了，检索的结果就是按照欧氏距离排序的

**Comment by 20TianTian22** [comment]
谢谢！我将您代码中计算map中的pos_set按照数据集调整了一下，现在map很高了，之前的pos_set是只依据训练集来设置的。
